INSERT INTO users (user_id,
                   username,
                   password,
                   first_name,
                   last_name,
                   email,
                   role,
                   creation_date,
                   enabled,
                   profile_image,
                   account_non_locked,
                   type,
                   deleted)
VALUES (0,
  'memoryleak',
  '$2a$04$WfBNZRG5lA27rgWgd4Kdf.I1B2gOrhcqFlnEC1GWB7cOm1B1yMQTy',
  'memoryleak',
  'memoryleak',
  'memoryleakofficial@gmail.com',
  'ROLE_ADMIN',
  '2017-01-01',
  TRUE,
  '/profileImage/admin.png',
  TRUE,
        '',
        FALSE
)