ALTER TABLE lectures
  ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE pages
  ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE questions
  ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users
  ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE virtual_classes
  ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE replies
  ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT false;
